// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testgopb/pb/dept/departments.proto

/*
Package dept is a generated protocol buffer package.

It is generated from these files:
	testgopb/pb/dept/departments.proto

It has these top-level messages:
	DepartmentsRes
	Department
	DepartmentsReq
*/
package pbdept

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
	"testgopb/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DepartmentsRes struct {
	Depts []*Department `protobuf:"bytes,1,rep,name=Depts" json:"Depts,omitempty"`
}

func (m *DepartmentsRes) Reset()                    { *m = DepartmentsRes{} }
func (m *DepartmentsRes) String() string            { return proto.CompactTextString(m) }
func (*DepartmentsRes) ProtoMessage()               {}
func (*DepartmentsRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DepartmentsRes) GetDepts() []*Department {
	if m != nil {
		return m.Depts
	}
	return nil
}

type Department struct {
	DeptId   int32  `protobuf:"varint,1,opt,name=DeptId" json:"DeptId,omitempty"`
	DeptName string `protobuf:"bytes,2,opt,name=DeptName" json:"DeptName,omitempty"`
}

func (m *Department) Reset()                    { *m = Department{} }
func (m *Department) String() string            { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()               {}
func (*Department) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Department) GetDeptId() int32 {
	if m != nil {
		return m.DeptId
	}
	return 0
}

func (m *Department) GetDeptName() string {
	if m != nil {
		return m.DeptName
	}
	return ""
}

type DepartmentsReq struct {
}

func (m *DepartmentsReq) Reset()                    { *m = DepartmentsReq{} }
func (m *DepartmentsReq) String() string            { return proto.CompactTextString(m) }
func (*DepartmentsReq) ProtoMessage()               {}
func (*DepartmentsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*DepartmentsRes)(nil), "dept.DepartmentsRes")
	proto.RegisterType((*Department)(nil), "dept.Department")
	proto.RegisterType((*DepartmentsReq)(nil), "dept.DepartmentsReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Departments service

type DepartmentsClient interface {
	GetDepartments(ctx context.Context, in *DepartmentsReq, opts ...client.CallOption) (*DepartmentsRes, error)
}

type departmentsClient struct {
	c           client.Client
	serviceName string
}

func NewDepartmentsClient(serviceName string, c client.Client) DepartmentsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = pb.ResolveSVCName
	}
	return &departmentsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *departmentsClient) GetDepartments(ctx context.Context, in *DepartmentsReq, opts ...client.CallOption) (*DepartmentsRes, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.GetDepartments", in)
	out := new(DepartmentsRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Departments service

type DepartmentsHandler interface {
	GetDepartments(context.Context, *DepartmentsReq, *DepartmentsRes) error
}

func RegisterDepartmentsHandler(s server.Server, hdlr DepartmentsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Departments{hdlr}, opts...))
}

type Departments struct {
	DepartmentsHandler
}

func (h *Departments) GetDepartments(ctx context.Context, in *DepartmentsReq, out *DepartmentsRes) error {
	return h.DepartmentsHandler.GetDepartments(ctx, in, out)
}

func init() { proto.RegisterFile("testgopb/pb/dept/departments.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x49, 0x2d, 0x2e,
	0x49, 0xcf, 0x2f, 0x48, 0xd2, 0x2f, 0x48, 0xd2, 0x4f, 0x49, 0x2d, 0x28, 0x01, 0x11, 0x89, 0x45,
	0x25, 0xb9, 0xa9, 0x79, 0x25, 0xc5, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0x71,
	0x25, 0x0b, 0x2e, 0x3e, 0x17, 0x84, 0x54, 0x50, 0x6a, 0xb1, 0x90, 0x1a, 0x17, 0xab, 0x4b, 0x6a,
	0x41, 0x49, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x80, 0x1e, 0x48, 0x9d, 0x1e, 0x42,
	0x51, 0x10, 0x44, 0x5a, 0xc9, 0x81, 0x8b, 0x0b, 0x21, 0x28, 0x24, 0xc6, 0xc5, 0x06, 0x12, 0xf6,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x40, 0x2c,
	0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x49, 0x00, 0xcd,
	0xee, 0x42, 0x23, 0x5f, 0x2e, 0x6e, 0x24, 0x11, 0x21, 0x3b, 0x2e, 0x3e, 0xf7, 0xd4, 0x12, 0x64,
	0x11, 0x11, 0x74, 0xd7, 0x80, 0xb4, 0x49, 0x61, 0x13, 0x2d, 0x56, 0x62, 0x48, 0x62, 0x03, 0xfb,
	0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x15, 0x4d, 0x10, 0xfb, 0x0f, 0x01, 0x00, 0x00,
}
